### ISSUE TITLE
Wine glasses not being counted properly

### ISSUE THREAD

**Issue by Mosolas** [DopiePanda/OholCurse#182]
**Describe the bug**
I recently went for the most wine drank record and it didn't count it at all, even looking at the life where I did it, it seems like it doesn't count the interactions with the wine glass. (The life was Pepe Freyre)
A while back I saw someone attempting it as well and it didn't count their attempt either.

**To Reproduce**
Interacting with wineglass a bunch and see if it counts it, I also have a video of the record attempt if necessary.

**Comment by DopiePanda** [comment]
Looking at it from the weekly leaderboard, it looks like it does record it;
https://oholcurse.com/leaderboards/weekly/object/3358

Remember that the map and life logs can be up to 24 hours delayed

**Comment by Mosolas** [comment]
> Remember that the map and life logs can be up to 24 hours delayed

It's been two days since the record attempt, even looking at the life itself it says item I interacted the most with that life is cabnet of grapes which is definitely not true.

Of course it's fine if you don't address this I'm just putting it out there

**Comment by DopiePanda** [comment]
Can you please share the life ID? You should be avble to find it in your "Lives" page on your player profile.

**Comment by Mosolas** [comment]
> Can you please share the life ID? You should be avble to find it in your "Lives" page on your player profile.

7369901

**Comment by DopiePanda** [comment]
Sorry for the extremely late reply on this. You should have brought it up in VC xD

![image](https://github.com/user-attachments/assets/f96b217b-5030-48b1-b901-fe79814054af)

That life ID only had 3 registered glasses on wine drank (or touched rather) out of the total 1974 actions registered for that life.
